version: 2

updates:
  - package-ecosystem: nuget
    directory: "/"
    target-branch: "development"
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 5
    labels:
      - dependencies
      - dotnet

  - package-ecosystem: github-actions
    directory: "/"
    target-branch: "development"
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 5
    labels:
      - dependencies
      - github-actions
