services:
  chatapp.api:
    image: ${DOCKER_REGISTRY-}chatappapi
    container_name: ChatApp.Api
    build:
      context: .
      dockerfile: src/ChatApp.Api/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80:80"

  chatapp-db:
    image: postgres:latest
    container_name: Chatapp.Db
    environment:
      - POSTGRES_DB=chatapp
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    # volumes:
    #   - ./.containers/database:/var/lib/postgresql/data
    ports:
      - 5432:5432
