name: CI - Build and Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Configurar .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "8.0.x"

      - name: Restaurar dependências
        run: |
          dotnet restore src/ChatApp.API/ChatApp.API.csproj
          dotnet restore tests/ChatApp.Tests/ChatApp.Tests.csproj

      - name: Compilar projeto principal
        run: dotnet build src/ChatApp.API/ChatApp.API.csproj --configuration Release --no-restore

      - name: Executar testes
        run: dotnet test tests/ChatApp.Tests/ChatApp.Tests.csproj --no-build --verbosity normal
