name: CI - Build and Test

on:
  push:
    branches:
      - main
      - development
  pull_request:
    branches:
      - main

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Configurar .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "8.0.x"

      - name: Restaurar dependências
        run: |
          dotnet restore

      - name: Compilar projeto principal
        run: dotnet build --no-restore ChatApp.sln

      - name: Executar testes
        run: dotnet test --no-build --no-restore ChatApp.sln
