name: Terraform Apply

on:
  push:
    branches:
      - main
    paths:
      - "infra/**"

permissions:
  contents: read
  id-token: write

jobs:
  apply:
    name: Apply (prod)
    runs-on: ubuntu-latest
    environment: production
    defaults:
      run:
        working-directory: infra/environments/prod

    steps:
      - name: Checkout do código
        uses: actions/checkout@v7

      - name: Configurar credenciais AWS (OIDC)
        uses: aws-actions/configure-aws-credentials@v6
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN_PROD }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "~> 1.6"

      - name: Terraform Init
        run: terraform init -input=false

      - name: Terraform Apply
        run: |
          terraform apply \
            -var-file="terraform.tfvars" \
            -var "jwt_secret_key=${{ secrets.TF_VAR_JWT_SECRET_KEY }}" \
            -auto-approve \
            -input=false
